version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=snip
      - POSTGRES_USER=password
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
  snip:
    build: .
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db